project:
  type: book
  output-dir: docs

book:
  title: "Documentación aplicada a la traducción"
  author: 
    - name: "Nicolas Robinson-Garcia"
      affiliation: "Universidad de Granada"
  language: es
  repo-url: https://github.com/elrobin/dat
  repo-actions: [edit, issue]
  sidebar:
    style: docked
    search: true
  navbar:
    background: primary
  chapters:
    - index.qmd
    - part: "9| La IA en el entorno académico"
      chapters:
        - tema9/sesion1.qmd
        - tema9/sesion2.qmd
        - tema9/sesion3.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 2
    toc-title: "En esta página"
    number-sections: false
    smooth-scroll: true
    code-fold: true
    code-tools: true
    highlight-style: github
    link-external-newwindow: true
    lang: es
